### PR TITLE
Added carousel in the homepage

### PR DESCRIPTION
**Pull request by artimanputra**
@mohit200008 Created a responsive carousel for the homepage for issue #4.

https://user-images.githubusercontent.com/79042027/145549489-20fa460b-c5d8-4c29-aeaf-f4f4911c5e36.mp4

### CODE REVIEW

**Comment by mohit200008** [comment]
The cover image above this has to be replaced with this carousel

**Comment by mohit200008** [comment]
Rest is good

**Comment by mohit200008** [comment]
Just see that the photos dont cover the text or button. on the cover photo

**Comment by artimanputra** [comment]
> Just see that the photos dont cover the text or button. on the cover photo

okay

**Comment by mohit200008** [comment]
can you send a final sc

**Comment by artimanputra** [comment]
Have a look on this
https://user-images.githubusercontent.com/79042027/145669113-af2eb393-f91c-4779-9168-f36f515375b4.mp4

**Comment by mohit200008** [comment]
good work @artimanputra

**Comment by artimanputra** [comment]
> good work @artimanputra

Thank You!

**Pull request merged**
