### PR TITLE
Added footer in the homepage

### PR DESCRIPTION
**Pull request by artimanputra**
@mohit200008 I have added a footer on the home page for issue #17. Do check out and let me know if any changes can be done. Then I will add that footer to all the pages.

https://user-images.githubusercontent.com/79042027/145786782-9547effe-9e5c-4ff4-b0ed-e6ce6270f61e.mp4

.

### CODE REVIEW

**Comment by mohit200008** [comment]
The footer and the navbar looks quite similar,  It could be made more appealing and the background of the footer can be bright.

**Comment by mohit200008** [comment]
The copyright section is okay , it could be placed at the bottom right of the footer , not below the chatbox

**Comment by mohit200008** [comment]
Can you redesign the footer and make a pr with just a ss of it.

**Comment by artimanputra** [comment]
> Can you redesign the footer and make a pr with just a ss of it. @artimanputra

sure I will

**Comment by artimanputra** [comment]
@mohit200008 This color will work?

https://user-images.githubusercontent.com/79042027/146352289-cafd9106-7acd-43c5-b3db-1e723286559d.mp4

**Comment by mohit200008** [comment]
on the footer you can give a input box to subscribe, Navlinks  in column direction , the copyright is in correct place and you can add the color has to be similar to white like off white or similar.

**Comment by artimanputra** [comment]
> on the footer you can give a input box to subscribe, Navlinks in column direction , the copyright is in correct place and you can add the color has to be similar to white like off white or similar.

Okay.

**Comment by mohit200008** [comment]
@artimanputra  any update on the footer design ?????

**Comment by artimanputra** [comment]
> @artimanputra any update on the footer design ?????

Yeah working on it

**Pull request closed without merging**
