### PR TITLE
Project Restructure 

### PR DESCRIPTION
**Pull request by aryasoni98**
#62

### CODE REVIEW

**Comment by mohit200008** [comment]
Is everything working as before ?? without any errors?

**Comment by aryasoni98** [comment]
@mohit200008 yes everything is working properly.
also add the labels and milestone

**Comment by mohit200008** [comment]
> @mohit200008 yes everything is working properly. also add the labels and milestone

on the PR or issue ???

**Comment by aryasoni98** [comment]
> > @mohit200008 yes everything is working properly. also add the labels and milestone
> 
> on the PR or issue ???

on the issue !

**Comment by aryasoni98** [comment]
Review my PR and merge it !

**Comment by mohit200008** [comment]
Can you connect with me tonight at 10 on discord

**Comment by aryasoni98** [comment]
Discord ID : aryasoni98#8991

**Pull request merged**
