### PR TITLE
Fixed routes in langauge button

### PR DESCRIPTION
**Pull request by prabhkaur301**
Fixed routes using conditional rendering in language toggle button in navbar.js & corrected some typos in Hindi translated homepage 

https://user-images.githubusercontent.com/57444962/158074186-cc77fa44-99ec-4ffe-9841-4fe5873e0174.mp4

### CODE REVIEW

**Comment by aktamoli0910** [comment]
There are some conflicts, please resolve them first.

**Comment by prabhkaur301** [comment]
> There are some conflicts, please resolve them first.

Resolved the conflicts. Kindly review it

**Comment by prabhkaur301** [comment]
Kindly label this PR under GSSOC for the countability

**Comment by prabhkaur301** [comment]
Please add the level label , so that marks can be counted

**Comment by mohit200008** [comment]
Issue number ?

**Comment by prabhkaur301** [comment]
> Issue number ?

#73

**Comment by prabhkaur301** [comment]
> #73

Kindly add level label to this PR 
Issue no - #73

**Pull request merged**
