### PR TITLE
"Doctor cards on the separate page" is done.

### PR DESCRIPTION
**Pull request by zugzwang03**
Hey Mohit sir, I have successfully made the cards section of doctors listing their specialization along with a button for set appointment.

### CODE REVIEW

**Comment by mohit200008** [comment]
can you share a screenshot @zugzwang03

**Comment by zugzwang03** [comment]
page1
page2

**Comment by mohit200008** [comment]
Okay

**Comment by zugzwang03** [comment]
Hey Mohit sir, I solved this issue under JWOC, but the respective PR count is not allotted to me there. Maybe you missed it...

**Pull request merged**
