### PR TITLE
Changed disease page UI - Issue #91

### PR DESCRIPTION
**Pull request by cybraia**
I have made new cards for the disease prediction page. Check it out and let me know if you want ant changes. 
Screenshot 2022-12-28 110905

### CODE REVIEW

**Comment by mohit200008** [comment]
can you also change the pictures and replace them with clear ones and also the cards are somewhat similar to previous ones

**Comment by cybraia** [comment]
Sure, I will change the pictures. Could you elaborate on what type of cards you want? Send a reference so I can code them.

**Comment by mohit200008** [comment]
The text inside the box should be clearly visible and readable and also the display should be in box format only when you hover it should zoom and the box should move slightly up

**Comment by cybraia** [comment]
Hi, I have done the changes as you said. Let me know if you have any other ideas to make it better. I have made sure there are 2 cards in each row and on the screen. When hovered, the card it zoomed. I have changed the images. 
image

**Comment by mohit200008** [comment]
Good work @cybraia

**Pull request merged**
