### PR TITLE
Beautify README.md

### PR DESCRIPTION
**Pull request by mandiraghosh783**
Here I have done few modifications.
I have added few emojis to make it look beautiful
Corrected the spelling errors and added punctuation marks wherever needed.

### CODE REVIEW

**Comment by mohit200008** [comment]
good work @mandiraghosh783

**Comment by mohit200008** [comment]
Can you add a how to contribute section too ??

**Comment by mandiraghosh783** [comment]
Suree!! I would love to do that too!!

**Comment by mandiraghosh783** [comment]
can you pls mention what all i have to write there??

**Comment by mohit200008** [comment]
Just create an issue of the same

**Comment by mohit200008** [comment]
> can you pls mention what all i have to write there??

You can refer any repo with a good how to contribute section.

**Pull request closed without merging**
