### PR TITLE
Breast Cancer Prediction

### PR DESCRIPTION
**Pull request by Shweta2024**
#### Related Issue
- Breast Cancer Prediction #85

#### Description
I have used the Wisconsin Breast Cancer Dataset for predicting Breast Cancer using Logistic Regression and Decision Tree Classifier.
- I have imported the required libraries
- followed by importing the dataset
- Performing Exploratory Data Analysis
- Data Visualization
- Splitting the dataset into test and train 
- Implementing the two models:- Logistic Regression & Decision Tree Classifier

#### Additional Link
- [Dataset link](https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data) 

#### Proposed Changes
- Add the Breast Cancer Prediction
#### Screenshots

image

image

image

image

image

### CODE REVIEW

**Comment by mohit200008** [comment]
Have you tested it on the website ??

**Comment by Shweta2024** [comment]
> Have you tested it on our website that its giving results or not?

### Sir this one?👇

image

**Comment by mohit200008** [comment]
Yes

**Comment by Shweta2024** [comment]
> Yes

Yes I did ,its giving results

**Pull request merged**
