### PR TITLE
Improved CSS in the Home Page as mentioned in issue #6

### PR DESCRIPTION
**Pull request by 25-vidushi**

### CODE REVIEW

**Comment by mohit200008** [comment]
can you send ss of the new layout ???

**Comment by 25-vidushi** [comment]
image
image

**Comment by mohit200008** [comment]
Can the navbar be shown even when the user have scrolled to bottom??

**Comment by mohit200008** [comment]
Rest its good work

**Comment by 25-vidushi** [comment]
No, the Navigation Bar isn't pinned. Should I make the changes??

**Comment by 25-vidushi** [comment]
Ok I'll make the changes.

**Comment by 25-vidushi** [comment]
image
This is the final NavBar. I chose the dark color only, as the bright ones weren't going with the home page picture.

**Comment by mohit200008** [comment]
Increase the border radius of the hover when any link on navbar is hovered and we're good to go.

**Comment by 25-vidushi** [comment]
image
I have made the changes.

**Comment by 25-vidushi** [comment]
I don't know how to add page transition. If you could provide with some resource to do so I can try implementing it.

**Comment by mohit200008** [comment]
Okay no problem , rest work is good

**Pull request merged**
