### PR TITLE
Changed Hindi home page similar to English home page

### PR DESCRIPTION
**Pull request by qadirpervez**
#33 Issue is fixed from this pull request

### CODE REVIEW

**Comment by mohit200008** [comment]
can you share a sc???

**Comment by mohit200008** [comment]
Make sure that the the design matches the english page. Even the photos and text below and CSS everything should  be same as english page.

**Comment by qadirpervez** [comment]
image

**Comment by qadirpervez** [comment]
Everything is similar to English home page, you can also see the images I used in the commits

**Pull request merged**
